version: '3.9'
volumes:
  node_modules:
services:
  nextjs-blog-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-blog-app
    volumes:
      - node_modules:/workspaces/nextjs-sample-blogapp/nextjs-app-dir-example/node_modules
    tty: true
    ports:
      - 3000:3000