version: '3.9'
#volumes:
#  node_modules:
services:
  nextjs-blog-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-blog-app
    #volumes:
    #  - ./prj/node_modules:/app/node_modules
    tty: true
    ports:
      - 3000:3000